### ISSUE TITLE
plan détaillé de la charte

### ISSUE THREAD

**Issue by jerryprincia0103** [iTeam-S/Dev-center#16]
[projet iTeam-S.docx](https://github.com/iTeam-S/Dev-center/files/5634383/projet.iTeam-S.docx)
@gaetan1903 
ito le izy

**Comment by gaetan1903** [comment]
lié à #4

**Comment by gaetan1903** [comment]
@jerryprincia0103  on associe donc au model ou comment ça se passe ?

**Comment by gaetan1903** [comment]
@jerryprincia0103 je met les fichiers dans un Google Doc, 

On remplira ensuite...

**Comment by gaetan1903** [comment]
Hello , 

Je relance,
l'organigramme est finaliser en version image
