### ISSUE TITLE
Site Vitrine 

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Dev-center#22]
@iTeam-S/iteam-ui-ux  

Pour notre présentation du 19 Décembre, nous avons besoin de notre site vitrine fonctionnel. 
 

### Site Statique avec ces pages: 

- [x] Accueil : Présentation  

- [ ] Projets : liste des projets avec détail, 

- [ ] Qui-sommes nous:

     -  Structure (organigramme), 
     -  Info chaque membre
     -  Mission équipe

- [x] Contact

- [ ]  Nous-rejoindre 

De asina page otrin portfolio ray na we CV, ampitovizana asina info détaillé chaque membre

**Comment by Xavier-001** [comment]
Bien reçu et mercii

**Comment by Smith-jpg** [comment]
bonjour , 
bien reçu.  @gaetan1903

**Comment by Landris18** [comment]
Tu peux compter sur mon équipe @gaetan1903

**Comment by hasintso2071** [comment]
c'est reçu.... @gaetan1903

**Comment by gaetan1903** [comment]
@iTeam-S/ui-ux  Assure ce tâche au plus tard le 17 Décembre svp...

**Comment by gaetan1903** [comment]
@iTeam-S/ui-ux 
On s'est dit le 17 Décembre.. la On est deja le 19 Decembre, 

tout est donc retarder 😞

**Comment by gaetan1903** [comment]
Salut,

je relance  @iTeam-S/ui-ux  

ça fait maintenant 1 mois que ce petit projet à été initier ... 

En attente de votre retour
