### ISSUE TITLE
Mise en place d'un API REST pour la communauté

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Dev-center#31]
Equipe @iTeam-S/back 

Suite à l'issue #19 [Conception et Modélisation des données] , 
Vous devez maintenant créer des routes pour récupérer chaque donnée dans la base.
Je remplirais cet issue à fur et à mesure.

 - Vous retournerez des données en format JSON.
 - Chaque route créer doit être documenter, à mettre dans la section wiki de GitHub et README
 -  Dispatchez bien les tâche, toute l'équipe doit participer à cette mise en place.

### API POUR FETCHER LES DONNEES 

- [x] Route qui retourne tous les membres 
- [x] Route qui retourne un info spécifique pour un membre 

Commencer par ça, on remplira au fur et à mesure les tâches à faires

**Comment by Ntsoa2112** [comment]
Bonsoir;

Je pense que nous devions discuter de la technologie que nous allons utiliser avant d'entamer une tache quelconque

**Comment by gaetan1903** [comment]
Bonsoir, 

libre à vous pour la technologie

**Comment by gaetan1903** [comment]
@Darcia2125 @salema02 @joseeange04  

C'est attribuer à vous,
refaite avec Laravel, 

J'ajouterai les fonctionnalité au fur et a mesure
