### ISSUE TITLE
Analyse des besoins de l'association , à court et moyen terme

### ISSUE THREAD

**Issue by Miadewa** [iTeam-S/Dev-center#32]
Salut tout le monde,

Alors, voici un fichier qui résume à peu près nos besoins dans les 3 mois à venir. Le tableau montre les besoins  en général (que ce soit à court ou à long terme), en bas, j'ai séparé les besoins en fonction d'un objectif précis par département afin de mieux cadrer notre travail. 
Je vous demande de remplir au fur et à mesure ce fichier, si vous trouvez des parties manquantes dans nos besoins, que ce soit à long et moyen terme (dans le tableau) ou à court terme (par section en bas). 

Dans cette longue liste, nous devons commencer par le business model avant de se concentrer sur les autres tâches. Pour se faire,  l'équipe admin doit se réunir avec 2 ou 3 représentants des développeurs. Normalement, on doit finir ça la semaine qui vient afin de préparer les autres dossiers qui viennent.

Voilà, bon courage à tous et à la prochaine
[Analyse de besoins à court.docx](https://github.com/iTeam-S/Dev-center/files/5703755/Analyse.de.besoins.a.court.docx)
[Analyse de besoins à court.docx](https://github.com/iTeam-S/Dev-center/files/5703758/Analyse.de.besoins.a.court.docx

**Comment by gaetan1903** [comment]
Salut, 
Pour que nous pussions travailler ensemble sur ce document, Je l'ai mis sur Google Doc.

Seul l'equipe @iTeam-S/admin ont accès avec vos mails.. 

En Attendant notre organisation pour le meet de la semaine prochaine,  On met en attente cet issue, 

Cependant, J'ajouterai quand même  quelque besoins technologique.


Merci

**Comment by Rojodev69** [comment]
Salut All, j'ai reçu ça sur mail: 
Assigned #32 to @RojoValisoa.

ça veut dire quoi?

**Comment by gaetan1903** [comment]
c'est déjà un sujet clos,

ça voulait dire que cet issue n°32 etait assigné à toi aussi,
