### ISSUE TITLE
ALANDIA

### ISSUE THREAD

**Issue by rootkit7628** [iTeam-S/Dev-center#34]
## Participants
- Dominick
- Arleme
- Gaetan

## Descriptions
Mobile : application de gestion de plantation
Website : Communauté pour partager savoir, problème et conseils

## Fonctionnalités :

- [ ] Mobile + Electronique 
     - [ ] Analyse du pH, Température ,humidité et luminosité 
     - [ ] Conseiller sur la plantation est adapté au lieu et climat
     - [ ] Suivre évolution et l'état + humidité + température + aération des plantes
     - [ ] Arrosage automatique des plantes si humité bas ou température haute
     - [ ] Arrosage à distance via l’application ou  message vocal 

- [ ] Site Web 
     - [ ] Communauté de cultivateurs (idées , conseils, problème)
     - [ ] Vente et Achat de plante, semence, outils de plantations, produit agricole
     - [ ] Challenge de plantation d’arbre 
     - [ ] Taux de contribution des uilisateurs à la nature et apport en oxygène

**Comment by gaetan1903** [comment]
tjr d'actualité @rootkit7628 ?

**Comment by rootkit7628** [comment]
> tjr d'actualité @rootkit7628 ?

A archiver je pense
