### ISSUE TITLE
ERP Sallon de coiffure

### ISSUE THREAD

**Issue by rootkit7628** [iTeam-S/Dev-center#35]
## Participants
- Arleme
- Gaetan

## Descriptions
Mise en place d'un ERP avec odoo pour un salon de coiffure

## Fonctionnalités :
- [ ] Gestion des recettes
     - [ ] POS
     - [ ]  Récapitulatifs des ventes
- [ ] Gestion des stocks  
     - Inventaire
     - Bon de commande
- [ ]  Gestion des clients 
     - [ ]  base de données/fiche clients
     - [ ]  Programme de fidélité
     - [ ]   Envoi d’E-mail aux clients pour promotion de produits

**Comment by gaetan1903** [comment]
Abondonné
