### ISSUE TITLE
Plan détaillé de la Charte

### ISSUE THREAD

**Issue by jerryprincia0103** [iTeam-S/Dev-center#4]
@gaetan1903 
organigramme de la communauté, les nombres de chaque organe
voir le fichier que je t'ai envoyé

**Comment by Landris18** [comment]
@jerryprincia0103, manja be zani organigramme ntsika zani😁😉

**Comment by gaetan1903** [comment]
D'accord, 
tu peux me renvoyer par mail, je n ai pas encore reçu le fichier...

**Comment by gaetan1903** [comment]
Clone du issue #16
